### ISSUE TITLE
IndexError: string index out of range in line 905

### ISSUE THREAD

**Issue by YourButterfly** [mrash/afl-cov#37]
[code](https://github.com/mrash/afl-cov/blob/70401e5824d40e7ccd7ef2f71eb91fb7938824df/afl-cov#L905)
```python
for part in cargs.coverage_cmd.split(' '):
            if part[0] == ' ' or part[0] == '-':
                continue
            if (which(part)):
                found_exec = True
                if not cargs.disable_gcov_check and is_bin_gcov_enabled(part, cargs):
                    found_code_cov_binary = True
                    break
```
if coverage_cmd has multi space, the value 'part'  will get a '' and making binary exit.like this
```
afl-cov -d /out --live --coverage-cmd "LD_LIBRARY_PATH=../lib/  ./tiffinfo -D AFL_FILE"   --code-dir /src/libtiff --genhtml-per-min 1440 --background
Traceback (most recent call last):
  File "/usr/local/bin/afl-cov", line 1236, in <module>
    sys.exit(main())
  File "/usr/local/bin/afl-cov", line 76, in main
    if not validate_cargs(cargs):
  File "/usr/local/bin/afl-cov", line 962, in validate_cargs
    if not is_gcov_enabled(cargs):
  File "/usr/local/bin/afl-cov", line 931, in is_gcov_enabled
    if part[0] == ' ' or part[0] == '-':
IndexError: string index out of range
```

**Comment by YourButterfly** [comment]
[try](https://github.com/YourButterfly/afl-cov/commit/ab0845f82941357473fec188e4f9a1c83b1fa2d1)

**Comment by mrash** [comment]
Fixed, thanks!
